      - name: Get commit message
        id: commit_msg
        run: echo "body<<EOF" >> $GITHUB_OUTPUT && git log -1 --format='%B' >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "v${{ github.run_number }}"
          body: ${{ steps.commit_msg.outputs.body }}
          files: .pio/build/esp32-c3-supermini/firmware.bin